- name: install > Packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - haproxy

- name: Enabling and starting HAproxy service
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Configuring HAproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: 'haproxy -f %s -c'
  notify: reload haproxy

- name: Enabling/Disabling net.ipv4.ip_nonlocal_bind option
  sysctl:
    nameL: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_file: /etc/sysctl.d/10-ip_nonlocal_bind.conf
    sysctl_set: yes
    reload: yes
    state: present
  notify: restart haproxy
  when: haproxy_bind_nonlocal_ip is defined and haproxy_bind_nonlocal_ip | bool

- name: services > Services
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - haproxy

